### ISSUE TITLE
Deeply nested schemas - how to construct into JSONSchema?

### ISSUE THREAD

**Issue by stringfellow** [fuhrysteve/marshmallow-jsonschema#32]
Say I have a deeply nested schema like this:

```

class D(Schema):
    f = fields.Int()

class C(Schema):
    e = fields.Str()

class B(Schema):
    c = fields.Nested(C)
    d = fields.Nested(D)

class A(Schema):
    b = fields.List(
        fields.Nested(B)
    )

```

How, when serialising `A()` with `JSONSchema` do you get the full representation (ultimately for use with `brutusin-jsonforms`)? At the moment it doesn't seem to automatically construct the inner schemas with `JSONSchema` - am I missing something?

**Comment by stringfellow** [comment]
Oh looks like you're totally solving this... ! Awesome :)

**Comment by fuhrysteve** [comment]
Yeah! Sorry forgot to post here - this should be fixed in 0.4.0 which I'll get up this afternoon at some point

**Comment by stringfellow** [comment]
@fuhrysteve thanks for the update - though it looks like lists still don't present the type if the type is `fields.Nested`, works OK for strings though

**Comment by fuhrysteve** [comment]
Interesting - ok. If you have a test case throw it up when you get a chance, otherwise I'll take a look at it as soon as I'm able.

**Comment by stringfellow** [comment]
Cool, am working on a PR for it

**Comment by tutuca** [comment]
This doesn't seem to support arbitrarily nested lists. Is there any workaround?

I'm working with a payload that looks like this:

```
{
    "name": "",
    "data": [
        "A", 
        [
            "B", 
            "C", 
            "D", 
            "E", 
            [
                "F", 
                [
                    "G", 
                    "J", 
                    "K"
                ], 
                [
                    "L", 
                    "M", 
                    "N"
                ]
            ]
        ], 
        "O"
    ]
}
``` 

So far I haven't got around the right incantation. I've tried casting it to a string or something but I'd really like for them to be lists.
